### ISSUE TITLE
KeyError 8L

### ISSUE THREAD

**Issue by statikregimen** [6e726d/PyWiWi#4]
When attempting to call queryInterface(someInterface, "current_connection") I receive the error shown below.

Here is the specific code I am using:
```
ifaces = pywiwi.getWirelessInterfaces()
for iface in ifaces:
    if iface.guid_string == targetGUID:
        routerName = pywiwi.queryInterface(
            iface,"current_connection"
        )[0].wlanAssociationAttributes.dot11Ssid.SSID
```

```
Traceback (most recent call last):
  File "auto-start_vpn.py", line 17, in <module>
    iface,"current_connection"
  File "C:\Panda3D-1.9.1\python\lib\pywiwi\WindowsWifi.py", line 376, in queryInterface
    "dot11PhyType": DOT11_PHY_TYPE_DICT[aa.dot11PhyType],
KeyError: 8L
```

I am able to work around this by commenting out the affected line (376 in WindowsWifi.py) but thought you might want to know.

Great module!!!

Thanks & Regards,
Mike

**Comment by 6e726d** [comment]
Thanks for the report.
I'm not working in this project at the moment, so I'm not sure if I will be able to test it and fix it.
